create table if not exists public.candidate_activity (
  id bigint generated by default as identity primary key,
  candidate_key text not null,
  candidate_name text,
  action_type text,
  action_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists candidate_activity_key_created_idx
  on public.candidate_activity(candidate_key, created_at desc);

alter table public.candidate_activity enable row level security;

drop policy if exists "candidate_activity_select" on public.candidate_activity;
drop policy if exists "candidate_activity_insert" on public.candidate_activity;

create policy "candidate_activity_select"
  on public.candidate_activity
  for select
  to anon
  using (true);

create policy "candidate_activity_insert"
  on public.candidate_activity
  for insert
  to anon
  with check (true);
