-- EvidenceHire: целевая схема для изолированной оценки кандидатов.
-- Скрипт идемпотентен и не удаляет старые таблицы или результаты проекта.
create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 160),
  retention_days integer not null default 365 check (retention_days between 30 and 3650),
  created_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','interviewer','viewer')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.job_profiles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  slug text not null,
  name text not null,
  family text not null default 'Другое',
  version integer not null default 1 check (version > 0),
  status text not null default 'draft' check (status in ('draft','expert_reviewed','pilot','validated','archived')),
  definition jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug, version)
);

create table if not exists public.candidates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  full_name text not null check (char_length(full_name) between 1 and 200),
  email text,
  consent_at timestamptz,
  retention_until date,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  job_profile_id uuid references public.job_profiles(id) on delete set null,
  profile_key text not null,
  status text not null default 'assessment' check (status in ('assessment','decision','closed')),
  final_decision text check (final_decision is null or final_decision in ('next','offer','reserve','decline')),
  decision_reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assessment_evidence (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  rater_id uuid not null references auth.users(id) on delete cascade,
  method text not null check (method in ('structured_interview','work_sample','eligibility','other')),
  item_id text not null,
  rating numeric(4,2) check (rating is null or rating between 1 and 5),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assessment_id, rater_id, method, item_id)
);

create table if not exists public.assessment_invites (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null default (now() + interval '7 days'),
  candidate_response text,
  consent_at timestamptz,
  submitted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.outcome_followups (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  checkpoint_days integer not null check (checkpoint_days in (30,60,90)),
  retained boolean,
  manager_rating numeric(4,2) check (manager_rating is null or manager_rating between 1 and 5),
  kpi_value numeric,
  kpi_definition text,
  notes text,
  recorded_by uuid references auth.users(id) on delete set null,
  recorded_at timestamptz not null default now(),
  unique (assessment_id, checkpoint_days)
);

create table if not exists public.hiring_audit_log (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  entity_id text,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists candidates_org_created_idx on public.candidates(organization_id, created_at desc);
create index if not exists assessments_org_created_idx on public.assessments(organization_id, created_at desc);
create index if not exists evidence_assessment_idx on public.assessment_evidence(assessment_id);
create index if not exists invites_assessment_idx on public.assessment_invites(assessment_id);
create index if not exists outcomes_assessment_idx on public.outcome_followups(assessment_id);

create or replace function public.is_org_member(target_org uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.organization_members m where m.organization_id = target_org and m.user_id = auth.uid()) $$;
revoke all on function public.is_org_member(uuid) from public, anon;
grant execute on function public.is_org_member(uuid) to authenticated;

create or replace function public.has_org_role(target_org uuid, accepted_roles text[])
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.organization_members m where m.organization_id = target_org and m.user_id = auth.uid() and m.role = any(accepted_roles)) $$;
revoke all on function public.has_org_role(uuid,text[]) from public, anon;
grant execute on function public.has_org_role(uuid,text[]) to authenticated;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.job_profiles enable row level security;
alter table public.candidates enable row level security;
alter table public.assessments enable row level security;
alter table public.assessment_evidence enable row level security;
alter table public.assessment_invites enable row level security;
alter table public.outcome_followups enable row level security;
alter table public.hiring_audit_log enable row level security;

drop policy if exists "members read organizations" on public.organizations;
create policy "members read organizations" on public.organizations for select to authenticated using (public.is_org_member(id));
drop policy if exists "owners update organizations" on public.organizations;
create policy "owners update organizations" on public.organizations for update to authenticated using (public.has_org_role(id,array['owner'])) with check (public.has_org_role(id,array['owner']));

drop policy if exists "members read memberships" on public.organization_members;
create policy "members read memberships" on public.organization_members for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists "owners manage memberships" on public.organization_members;
create policy "owners manage memberships" on public.organization_members for all to authenticated using (public.has_org_role(organization_id,array['owner'])) with check (public.has_org_role(organization_id,array['owner']));

drop policy if exists "members read profiles" on public.job_profiles;
create policy "members read profiles" on public.job_profiles for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists "admins manage profiles" on public.job_profiles;
create policy "admins manage profiles" on public.job_profiles for all to authenticated using (public.has_org_role(organization_id,array['owner','admin'])) with check (public.has_org_role(organization_id,array['owner','admin']));

drop policy if exists "members read candidates" on public.candidates;
create policy "members read candidates" on public.candidates for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists "staff create candidates" on public.candidates;
create policy "staff create candidates" on public.candidates for insert to authenticated with check (public.has_org_role(organization_id,array['owner','admin','interviewer']) and created_by = auth.uid());
drop policy if exists "admins update candidates" on public.candidates;
create policy "admins update candidates" on public.candidates for update to authenticated using (public.has_org_role(organization_id,array['owner','admin'])) with check (public.has_org_role(organization_id,array['owner','admin']));
drop policy if exists "admins delete candidates" on public.candidates;
create policy "admins delete candidates" on public.candidates for delete to authenticated using (public.has_org_role(organization_id,array['owner','admin']));

drop policy if exists "members read assessments" on public.assessments;
create policy "members read assessments" on public.assessments for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists "staff create assessments" on public.assessments;
create policy "staff create assessments" on public.assessments for insert to authenticated with check (public.has_org_role(organization_id,array['owner','admin','interviewer']) and created_by = auth.uid());
drop policy if exists "staff update assessments" on public.assessments;
create policy "staff update assessments" on public.assessments for update to authenticated using (public.has_org_role(organization_id,array['owner','admin','interviewer'])) with check (public.has_org_role(organization_id,array['owner','admin','interviewer']));
drop policy if exists "admins delete assessments" on public.assessments;
create policy "admins delete assessments" on public.assessments for delete to authenticated using (public.has_org_role(organization_id,array['owner','admin']));

drop policy if exists "raters read own evidence" on public.assessment_evidence;
create policy "raters read own evidence" on public.assessment_evidence for select to authenticated using (public.has_org_role(organization_id,array['owner','admin']) or (public.is_org_member(organization_id) and rater_id = auth.uid()));
drop policy if exists "raters create own evidence" on public.assessment_evidence;
create policy "raters create own evidence" on public.assessment_evidence for insert to authenticated with check (public.has_org_role(organization_id,array['owner','admin','interviewer']) and rater_id = auth.uid());
drop policy if exists "raters update own evidence" on public.assessment_evidence;
create policy "raters update own evidence" on public.assessment_evidence for update to authenticated using (rater_id = auth.uid() and public.is_org_member(organization_id)) with check (rater_id = auth.uid() and public.is_org_member(organization_id));
drop policy if exists "admins delete evidence" on public.assessment_evidence;
create policy "admins delete evidence" on public.assessment_evidence for delete to authenticated using (public.has_org_role(organization_id,array['owner','admin']) or rater_id = auth.uid());

drop policy if exists "admins read invites" on public.assessment_invites;
create policy "admins read invites" on public.assessment_invites for select to authenticated using (public.has_org_role(organization_id,array['owner','admin']));
drop policy if exists "admins manage invites" on public.assessment_invites;
create policy "admins manage invites" on public.assessment_invites for all to authenticated using (public.has_org_role(organization_id,array['owner','admin'])) with check (public.has_org_role(organization_id,array['owner','admin']));

drop policy if exists "admins read outcomes" on public.outcome_followups;
create policy "admins read outcomes" on public.outcome_followups for select to authenticated using (public.has_org_role(organization_id,array['owner','admin']));
drop policy if exists "admins manage outcomes" on public.outcome_followups;
create policy "admins manage outcomes" on public.outcome_followups for all to authenticated using (public.has_org_role(organization_id,array['owner','admin'])) with check (public.has_org_role(organization_id,array['owner','admin']));

drop policy if exists "admins read audit" on public.hiring_audit_log;
create policy "admins read audit" on public.hiring_audit_log for select to authenticated using (public.has_org_role(organization_id,array['owner','admin']));

create or replace function public.create_assessment_invite(target_assessment uuid)
returns text language plpgsql security definer set search_path = public
as $$
declare raw_token text := encode(gen_random_bytes(32),'hex'); target_org uuid;
begin
  select organization_id into target_org from public.assessments where id = target_assessment;
  if target_org is null or not public.has_org_role(target_org,array['owner','admin']) then raise exception 'not authorized'; end if;
  insert into public.assessment_invites(organization_id,assessment_id,token_hash,created_by)
  values(target_org,target_assessment,encode(digest(raw_token,'sha256'),'hex'),auth.uid());
  return raw_token;
end $$;
revoke all on function public.create_assessment_invite(uuid) from public, anon;
grant execute on function public.create_assessment_invite(uuid) to authenticated;

create or replace function public.get_candidate_assignment(raw_token text)
returns table(assessment_id uuid,candidate_name text,profile_key text,profile_definition jsonb,candidate_response text,submitted_at timestamptz,expires_at timestamptz)
language sql stable security definer set search_path = public
as $$
  select a.id,c.full_name,a.profile_key,coalesce(j.definition,'null'::jsonb),i.candidate_response,i.submitted_at,i.expires_at
  from public.assessment_invites i join public.assessments a on a.id=i.assessment_id join public.candidates c on c.id=a.candidate_id
  left join public.job_profiles j on j.id=a.job_profile_id
  where i.token_hash=encode(digest(raw_token,'sha256'),'hex') and i.expires_at>now()
  limit 1
$$;
revoke all on function public.get_candidate_assignment(text) from public, authenticated;
grant execute on function public.get_candidate_assignment(text) to anon;

create or replace function public.submit_candidate_assignment(raw_token text,response_text text,consent_given boolean)
returns boolean language plpgsql security definer set search_path = public
as $$
declare changed integer;
begin
  if consent_given is not true or char_length(trim(response_text)) < 20 or char_length(response_text) > 20000 then return false; end if;
  update public.assessment_invites set candidate_response=response_text,consent_at=now(),submitted_at=now()
  where token_hash=encode(digest(raw_token,'sha256'),'hex') and expires_at>now() and submitted_at is null;
  get diagnostics changed = row_count;
  return changed=1;
end $$;
revoke all on function public.submit_candidate_assignment(text,text,boolean) from public, authenticated;
grant execute on function public.submit_candidate_assignment(text,text,boolean) to anon;

create or replace function public.purge_expired_candidates()
returns integer language plpgsql security definer set search_path = public
as $$ declare removed integer; begin
  delete from public.candidates where retention_until is not null and retention_until < current_date;
  get diagnostics removed = row_count;
  return removed;
end $$;
revoke all on function public.purge_expired_candidates() from public, anon, authenticated;
